
<AdminDB>:


    canvas:
        Color:
            rgba: 0,1,1,1
        Rectangle:
            pos:100,600
            size:900,100
        on_pre_enter:
            canvas.clear()
    Button:
        text: 'hello'
        pos: 100,100
        size: 200,200
        on_press: canvas.clear()
    Label:
        text: 'putangina niyo'
        pos: 500,600
        color: 0,0,0,1
        font_size: 24
        bold: True